Zihao dev
NEVSTOP-LAB/NEVSTOP-Programming-Palette pull request #147
Opened 2023-05-15 09:52 UTC by Onsen-eggs

Add Time @nevstop #130 
Owner: Zihao Wei
添加了时间部分，后续会继续添加，谢谢~

2023-05-30 08:31 UTC, Onsen-eggs commented
@nevstop 已完成，请使用最新的commit，谢谢。

2023-05-31 03:32 UTC, nevstop requested changes
代码没有用2017 开发，需要保存到2017
![image](https://github.com/NEVSTOP-LAB/NEVSTOP-Programming-Palette/assets/8196752/872467d8-b203-464c-832f-d3ae9fd5b4bb)

2023-06-01 00:57 UTC, nevstop commented
@Onsen-eggs 所以这个 PR 中的修改没有必要啦？我直接关掉可以吗？

2023-06-01 02:06 UTC, Onsen-eggs commented
@nevstop 嗯嗯是的，感谢~

2023-06-01 02:18 UTC, closed without merging